version: "3.1"

volumes:
  sqldb:

networks:
  sqlnetwork:

services:
  backend:
    image: php:8.2-apache
    restart: unless-stopped
    build:
      context: .
      dockerfile: DockerfilePHP
    environment:
      - MYSQL_DBHOST=db
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DBNAME=react-php
    ports:
      - 8000:80
    networks:
      - sqlnetwork
    depends_on:
      - db

  frontend:
    image: nginx:alpine
    container_name: frontend
    build:
      context: .
      dockerfile: DockerfileREACT
    restart: always
    ports:
      - 5173:80
    networks:
      - sqlnetwork

  db:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - sqldb:/var/lib/mysql
    networks:
      - sqlnetwork
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - 8181:80
    networks:
      - sqlnetwork
