version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php:/var/www/html
    ports:
      - 8000:80  
    networks:
      - sqlnetwork
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: ./React
      dockerfile: Dockerfile
    volumes:
      - ./React:/usr/share/nginx/html
    ports:
      - "5173:80"
    depends_on:
      - backend

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: react-php
    volumes:
      - sqldb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - sqlnetwork

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8181:80"
    networks:
      - sqlnetwork

networks:
  sqlnetwork:

volumes:
  sqldb:
