version: "3.9"

services:
  backend:
    container_name: backend
    image: manuel393/backend-reactphp:v1.0
    ports:
      - "8000:80"
    networks:
      - sqlnetwork
    depends_on:
      - db

  frontend-1:
    container_name: frontend-1
    build:
      context: React/
      args:
        REACT_APP_REPLICA_NUM: 1
    expose:
      - "80"
    ports:
      - "3001:80"
    environment:
      - NUM_FRONTEND=1
    depends_on:
      - backend
    networks:
      - webnetwork

  frontend-2:
    container_name: frontend-2
    build:
      context: React/
      args:
        REACT_APP_REPLICA_NUM: 2
    expose:
      - "80"
    ports:
      - "3002:80"
    environment:
      - NUM_FRONTEND=2
    depends_on:
      - backend
    networks:
      - webnetwork

  frontend-3:
    container_name: frontend-3
    build:
      context: React/
      args:
        REACT_APP_REPLICA_NUM: 3
    expose:
      - "80"
    ports:
      - "3003:80"
    environment:
      - NUM_FRONTEND=3
    depends_on:
      - backend
    networks:
      - webnetwork

  nginx:
    build: ./nginx
    ports:
      - "5173:80"
    networks:
      - webnetwork
    depends_on:
      - frontend-1
      - frontend-2
      - frontend-3

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: react-php
    volumes:
      - sqldb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - sqlnetwork

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8181:80"
    networks:
      - sqlnetwork

networks:
  sqlnetwork:
  webnetwork:

volumes:
  sqldb:
