apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/sqlnetwork: "true"
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: MYSQL_DBHOST
              value: db
            - name: MYSQL_DBNAME
              value: react-php
            - name: MYSQL_DBPASS
              value: password
            - name: MYSQL_DBPORT
              value: "3306"
            - name: MYSQL_DBUSER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              value: password
          image: php:8.2-apache
          name: backend
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html
              name: backend-claim0
      restartPolicy: Always
      volumes:
        - name: backend-claim0
          persistentVolumeClaim:
            claimName: backend-claim0
status: {}
