import requests
import json

# Data to send
body_parts = [
    {
        "is_body_part": True,
        "length": 15,
        "height": 10,
        "thickness": 2,
        "weight": 0.8,
        "price": 40,
        "ship_time": 24,
        "availability": 90,
        "bd_name": "Parafango Anteriore",
        "bd_description": "Parafango anteriore in plastica rinforzata.",
        "bid_provider": 17,
        "year": 2021,
        "color": "Rosso",
        "vehicle_model": "KTM 250 SX"
    },
    {
        "is_body_part": True,
        "length": 20,
        "height": 15,
        "thickness": 3,
        "weight": 1.0,
        "price": 60,
        "ship_time": 48,
        "availability": 85,
        "bd_name": "Serbatoio Carburante",
        "bd_description": "Serbatoio carburante in alluminio per moto da enduro.",
        "bid_provider": 18,
        "year": 2022,
        "color": "Blu",
        "vehicle_model": "Yamaha WR250F"
    },
    {
        "is_body_part": True,
        "length": 30,
        "height": 20,
        "thickness": 4,
        "weight": 1.5,
        "price": 80,
        "ship_time": 36,
        "availability": 80,
        "bd_name": "Coda Moto",
        "bd_description": "Coda moto con supporto per luci e indicatori.",
        "bid_provider": 19,
        "year": 2020,
        "color": "Nero",
        "vehicle_model": "Honda CRF450R"
    },
    {
        "is_body_part": True,
        "length": 25,
        "height": 15,
        "thickness": 3,
        "weight": 1.2,
        "price": 65,
        "ship_time": 48,
        "availability": 90,
        "bd_name": "Paraurti Posteriore",
        "bd_description": "Para indipendente in plastica per protezione posteriore.",
        "bid_provider": 17,
        "year": 2022,
        "color": "Verde",
        "vehicle_model": "Kawasaki KX450F"
    },
    {
        "is_body_part": True,
        "length": 15,
        "height": 12,
        "thickness": 2,
        "weight": 0.9,
        "price": 45,
        "ship_time": 24,
        "availability": 95,
        "bd_name": "Copri Carburatore",
        "bd_description": "Copertura del carburatore in plastica resistente al calore.",
        "bid_provider": 18,
        "year": 2021,
        "color": "Arancione",
        "vehicle_model": "Husqvarna TE300"
    },
    {
        "is_body_part": True,
        "length": 20,
        "height": 20,
        "thickness": 4,
        "weight": 1.7,
        "price": 75,
        "ship_time": 36,
        "availability": 85,
        "bd_name": "Fianchetto Laterale",
        "bd_description": "Fianchetto laterale in plastica per migliorare l'aerodinamica.",
        "bid_provider": 19,
        "year": 2022,
        "color": "Giallo",
        "vehicle_model": "Suzuki RM-Z450"
    },
    {
        "is_body_part": True,
        "length": 25,
        "height": 10,
        "thickness": 3,
        "weight": 1.0,
        "price": 50,
        "ship_time": 48,
        "availability": 80,
        "bd_name": "Mascherina Faro",
        "bd_description": "Mascherina del faro anteriore con protezione aggiuntiva.",
        "bid_provider": 17,
        "year": 2021,
        "color": "Nero",
        "vehicle_model": "KTM 350 EXC-F"
    },
    {
        "is_body_part": True,
        "length": 30,
        "height": 15,
        "thickness": 4,
        "weight": 1.8,
        "price": 70,
        "ship_time": 36,
        "availability": 85,
        "bd_name": "Cupolino",
        "bd_description": "Cupolino aerodinamico per migliorare la velocità.",
        "bid_provider": 18,
        "year": 2020,
        "color": "Grigio",
        "vehicle_model": "Yamaha YZF-R1"
    },
    {
        "is_body_part": True,
        "length": 35,
        "height": 20,
        "thickness": 5,
        "weight": 2.0,
        "price": 90,
        "ship_time": 48,
        "availability": 75,
        "bd_name": "Serbatoio Olio",
        "bd_description": "Serbatoio dell'olio per moto da corsa.",
        "bid_provider": 19,
        "year": 2022,
        "color": "Rosso",
        "vehicle_model": "Ducati Panigale V4"
    },
    {
        "is_body_part": True,
        "length": 25,
        "height": 15,
        "thickness": 3,
        "weight": 1.3,
        "price": 60,
        "ship_time": 36,
        "availability": 80,
        "bd_name": "Sella Moto",
        "bd_description": "Sella in gel per massimo comfort.",
        "bid_provider": 17,
        "year": 2021,
        "color": "Blu",
        "vehicle_model": "Kawasaki KX250F"
    },
    {
        "is_body_part": True,
        "length": 20,
        "height": 12,
        "thickness": 2,
        "weight": 1.0,
        "price": 50,
        "ship_time": 24,
        "availability": 95,
        "bd_name": "Parafango Posteriore",
        "bd_description": "Parafango posteriore in plastica leggera.",
        "bid_provider": 18,
        "year": 2022,
        "color": "Verde",
        "vehicle_model": "Husqvarna TE150"
    },
    {
        "is_body_part": True,
        "length": 25,
        "height": 20,
        "thickness": 4,
        "weight": 1.8,
        "price": 70,
        "ship_time": 36,
        "availability": 80,
        "bd_name": "Mascherina Parabrezza",
        "bd_description": "Mascherina per parabrezza con protezione UV.",
        "bid_provider": 19,
        "year": 2021,
        "color": "Nero",
        "vehicle_model": "BMW S1000RR"
    },
    {
        "is_body_part": True,
        "length": 35,
        "height": 25,
        "thickness": 5,
        "weight": 2.2,
        "price": 85,
        "ship_time": 48,
        "availability": 75,
        "bd_name": "Parafango Laterale",
        "bd_description": "Parafango laterale in fibra di carbonio.",
        "bid_provider": 18,
        "year": 2022,
        "color": "Grigio",
        "vehicle_model": "Suzuki GSX-R1000"
    },
    {
        "is_body_part": True,
        "length": 20,
        "height": 15,
        "thickness": 3,
        "weight": 1.0,
        "price": 55,
        "ship_time": 24,
        "availability": 90,
        "bd_name": "Copertura Catena",
        "bd_description": "Copertura della catena in plastica rinforzata.",
        "bid_provider": 19,
        "year": 2021,
        "color": "Nero",
        "vehicle_model": "Ducati Monster 821"
    },
    {
        "is_body_part": True,
        "length": 25,
        "height": 15,
        "thickness": 3,
        "weight": 1.2,
        "price": 60,
        "ship_time": 36,
        "availability": 80,
        "bd_name": "Coperchio Motore",
        "bd_description": "Coperchio del motore in alluminio anodizzato.",
        "bid_provider": 17,
        "year": 2022,
        "color": "Rosso",
        "vehicle_model": "Yamaha YZF-R6"
    },
    {
        "is_body_part": True,
        "length": 30,
        "height": 20,
        "thickness": 4,
        "weight": 1.7,
        "price": 75,
        "ship_time": 36,
        "availability": 85,
        "bd_name": "Parafango Anteriore",
        "bd_description": "Parafango anteriore in fibra di carbonio.",
        "bid_provider": 18,
        "year": 2021,
        "color": "Blu",
        "vehicle_model": "Triumph Tiger 900"
    },
    {
        "is_body_part": True,
        "length": 35,
        "height": 15,
        "thickness": 4,
        "weight": 1.9,
        "price": 80,
        "ship_time": 48,
        "availability": 80,
        "bd_name": "Coda Moto",
        "bd_description": "Coda moto in plastica resistente e leggera.",
        "bid_provider": 19,
        "year": 2022,
        "color": "Nero",
        "vehicle_model": "Honda CB500X"
    },
    {
        "is_body_part": True,
        "length": 20,
        "height": 12,
        "thickness": 2,
        "weight": 0.8,
        "price": 45,
        "ship_time": 24,
        "availability": 90,
        "bd_name": "Copertura Specchietti",
        "bd_description": "Copertura degli specchietti in plastica nera.",
        "bid_provider": 18,
        "year": 2022,
        "color": "Nero",
        "vehicle_model": "MV Augusta F3 800"
    },
    {
        "is_body_part": True,
        "length": 30,
        "height": 20,
        "thickness": 5,
        "weight": 1.8,
        "price": 80,
        "ship_time": 48,
        "availability": 85,
        "bd_name": "Serbatoio Carburante",
        "bd_description": "Serbatoio carburante in fibra di carbonio per massima leggerezza.",
        "bid_provider": 17,
        "year": 2021,
        "color": "Verde",
        "vehicle_model": "BMW R1250GS"
    },
    {
        "is_body_part": True,
        "length": 25,
        "height": 15,
        "thickness": 3,
        "weight": 1.2,
        "price": 55,
        "ship_time": 36,
        "availability": 80,
        "bd_name": "Sella Moto",
        "bd_description": "Sella ergonomica per una guida confortevole.",
        "bid_provider": 18,
        "year": 2020,
        "color": "Grigio",
        "vehicle_model": "Harley Davidson Sportster"
    },
    {
        "is_body_part": True,
        "length": 35,
        "height": 25,
        "thickness": 4,
        "weight": 2.2,
        "price": 90,
        "ship_time": 48,
        "availability": 75,
        "bd_name": "Cupolino",
        "bd_description": "Cupolino in plastica rinforzata con protezione UV.",
        "bid_provider": 19,
        "year": 2022,
        "color": "Nero",
        "vehicle_model": "Kawasaki Z900"
    },
    {
        "is_body_part": True,
        "length": 25,
        "height": 20,
        "thickness": 4,
        "weight": 1.5,
        "price": 65,
        "ship_time": 36,
        "availability": 85,
        "bd_name": "Parafango Posteriore",
        "bd_description": "Parafango posteriore in plastica resistente agli urti.",
        "bid_provider": 17,
        "year": 2021,
        "color": "Blu",
        "vehicle_model": "Yamaha MT-07"
    },
    {
        "is_body_part": True,
        "length": 30,
        "height": 20,
        "thickness": 5,
        "weight": 1.8,
        "price": 75,
        "ship_time": 36,
        "availability": 80,
        "bd_name": "Serbatoio Olio",
        "bd_description": "Serbatoio olio con alta capacità e resistenza.",
        "bid_provider": 18,
        "year": 2022,
        "color": "Nero",
        "vehicle_model": "Honda CBR1000RR"
    }
]



mechanical_parts = [
    {
        "is_body_part": False,
        "length": 20,
        "height": 10,
        "thickness": 2,
        "weight": 1.0,
        "price": 50,
        "ship_time": 24,
        "availability": 95,
        "mp_name": "Pompa Frizione",
        "mp_description": "Pompa frizione con alta resistenza e prestazioni elevate.",
        "mid_provider": 17,
        "year_from": 2018,
        "year_to": 2023,
        "builds_on": "KV,YM"
    },
    {
        "is_body_part": False,
        "length": 25,
        "height": 15,
        "thickness": 3,
        "weight": 1.5,
        "price": 80,
        "ship_time": 48,
        "availability": 85,
        "mp_name": "Cinghia Trasmissione",
        "mp_description": "Cinghia di trasmissione ad alte prestazioni per moto da enduro.",
        "mid_provider": 18,
        "year_from": 2021,
        "year_to": 2024,
        "builds_on": "HN,KV,KM"
    },
    {
        "is_body_part": False,
        "length": 30,
        "height": 20,
        "thickness": 4,
        "weight": 2.0,
        "price": 110,
        "ship_time": 24,
        "availability": 75,
        "mp_name": "Cambio",
        "mp_description": "Cambio per moto da strada con ingranaggi rinforzati.",
        "mid_provider": 19,
        "year_from": 2019,
        "year_to": 2023,
        "builds_on": "YM,BW,DC"
    },
    {
        "is_body_part": False,
        "length": 15,
        "height": 10,
        "thickness": 3,
        "weight": 0.8,
        "price": 60,
        "ship_time": 48,
        "availability": 90,
        "mp_name": "Regolatore di Tensione",
        "mp_description": "Regolatore di tensione per sistemi di accensione elettronica.",
        "mid_provider": 19,
        "year_from": 2022,
        "year_to": 2024,
        "builds_on": "MG,SZ"
    },
    {
        "is_body_part": False,
        "length": 35,
        "height": 15,
        "thickness": 4,
        "weight": 2.2,
        "price": 95,
        "ship_time": 36,
        "availability": 80,
        "mp_name": "Pompa Benzina",
        "mp_description": "Pompa benzina ad alta pressione per moto sportive.",
        "mid_provider": 18,
        "year_from": 2020,
        "year_to": 2023,
        "builds_on": "DC,YM,KM"
    },
    {
        "is_body_part": False,
        "length": 40,
        "height": 25,
        "thickness": 5,
        "weight": 2.5,
        "price": 120,
        "ship_time": 48,
        "availability": 70,
        "mp_name": "Motore",
        "mp_description": "Motore 4 tempi con alte prestazioni.",
        "mid_provider": 17,
        "year_from": 2021,
        "year_to": 2024,
        "builds_on": "KV,KM,BW"
    },
    {
        "is_body_part": False,
        "length": 20,
        "height": 15,
        "thickness": 3,
        "weight": 1.2,
        "price": 55,
        "ship_time": 36,
        "availability": 85,
        "mp_name": "Valvola di Scarico",
        "mp_description": "Valvola di scarico in acciaio inox ad alte prestazioni.",
        "mid_provider": 18,
        "year_from": 2020,
        "year_to": 2023,
        "builds_on": "HN,KM,SZ"
    },
    {
        "is_body_part": False,
        "length": 30,
        "height": 15,
        "thickness": 4,
        "weight": 1.7,
        "price": 90,
        "ship_time": 48,
        "availability": 75,
        "mp_name": "Sistema di Raffreddamento",
        "mp_description": "Sistema di raffreddamento per moto da competizione.",
        "mid_provider": 19,
        "year_from": 2019,
        "year_to": 2024,
        "builds_on": "YM,SZ,DC"
    },
    {
        "is_body_part": False,
        "length": 25,
        "height": 10,
        "thickness": 3,
        "weight": 1.3,
        "price": 70,
        "ship_time": 24,
        "availability": 90,
        "mp_name": "Pistone",
        "mp_description": "Pistone in lega leggera per moto da cross.",
        "mid_provider": 17,
        "year_from": 2022,
        "year_to": 2024,
        "builds_on": "KM,SZ,YM"
    },
    {
        "is_body_part": False,
        "length": 35,
        "height": 20,
        "thickness": 5,
        "weight": 2.2,
        "price": 100,
        "ship_time": 36,
        "availability": 85,
        "mp_name": "Albero a Camme",
        "mp_description": "Albero a camme con profilo sportivo per migliorare le prestazioni.",
        "mid_provider": 18,
        "year_from": 2021,
        "year_to": 2023,
        "builds_on": "YM,BW,DC"
    },
    {
        "is_body_part": False,
        "length": 45,
        "height": 25,
        "thickness": 6,
        "weight": 2.8,
        "price": 140,
        "ship_time": 48,
        "availability": 70,
        "mp_name": "Cambio Rapido",
        "mp_description": "Cambio rapido per moto da corsa con tecnologia avanzata.",
        "mid_provider": 19,
        "year_from": 2020,
        "year_to": 2024,
        "builds_on": "DC,YM,KM"
    },
    {
        "is_body_part": False,
        "length": 25,
        "height": 15,
        "thickness": 3,
        "weight": 1.5,
        "price": 65,
        "ship_time": 48,
        "availability": 80,
        "mp_name": "Sensore di Temperatura",
        "mp_description": "Sensore di temperatura per motori di alta precisione.",
        "mid_provider": 17,
        "year_from": 2022,
        "year_to": 2024,
        "builds_on": "BMW,HV,KM"
    },
    {
        "is_body_part": False,
        "length": 30,
        "height": 20,
        "thickness": 4,
        "weight": 1.9,
        "price": 85,
        "ship_time": 36,
        "availability": 90,
        "mp_name": "Ammortizzatore Posteriore",
        "mp_description": "Ammortizzatore posteriore con regolazione elettronica.",
        "mid_provider": 18,
        "year_from": 2021,
        "year_to": 2023,
        "builds_on": "YZ,KM,YM"
    },
    {
        "is_body_part": False,
        "length": 20,
        "height": 12,
        "thickness": 2,
        "weight": 1.0,
        "price": 50,
        "ship_time": 24,
        "availability": 95,
        "mp_name": "Filtro Aria",
        "mp_description": "Filtro aria ad alta capacità di filtraggio per motori sportivi.",
        "mid_provider": 19,
        "year_from": 2022,
        "year_to": 2024,
        "builds_on": "KM,YM,DC"
    },
    {
        "is_body_part": False,
        "length": 35,
        "height": 15,
        "thickness": 4,
        "weight": 1.8,
        "price": 95,
        "ship_time": 48,
        "availability": 85,
        "mp_name": "Pompa dell'Olio",
        "mp_description": "Pompa dell'olio ad alte prestazioni per moto da corsa.",
        "mid_provider": 17,
        "year_from": 2020,
        "year_to": 2023,
        "builds_on": "KM,YM,DC"
    },
    {
        "is_body_part": False,
        "length": 25,
        "height": 10,
        "thickness": 3,
        "weight": 1.2,
        "price": 60,
        "ship_time": 24,
        "availability": 90,
        "mp_name": "Rettifica Cilindro",
        "mp_description": "Rettifica cilindro per migliorare le prestazioni del motore.",
        "mid_provider": 18,
        "year_from": 2021,
        "year_to": 2024,
        "builds_on": "DC,YM,SZ"
    },
    {
        "is_body_part": False,
        "length": 30,
        "height": 20,
        "thickness": 4,
        "weight": 2.0,
        "price": 85,
        "ship_time": 36,
        "availability": 75,
        "mp_name": "Carter di Copertura",
        "mp_description": "Carter di copertura in alluminio per motori sportivi.",
        "mid_provider": 19,
        "year_from": 2020,
        "year_to": 2023,
        "builds_on": "KM,DC,YM"
    },
    {
        "is_body_part": False,
        "length": 25,
        "height": 15,
        "thickness": 3,
        "weight": 1.4,
        "price": 70,
        "ship_time": 48,
        "availability": 80,
        "mp_name": "Pompa Frizione",
        "mp_description": "Pompa frizione con alta resistenza e prestazioni elevate.",
        "mid_provider": 17,
        "year_from": 2022,
        "year_to": 2024,
        "builds_on": "KM,YM,DC"
    },
    {
        "is_body_part": False,
        "length": 40,
        "height": 25,
        "thickness": 5,
        "weight": 2.5,
        "price": 130,
        "ship_time": 48,
        "availability": 70,
        "mp_name": "Alternatore",
        "mp_description": "Alternatore ad alte prestazioni per moto da competizione.",
        "mid_provider": 19,
        "year_from": 2021,
        "year_to": 2023,
        "builds_on": "DC,YM,KM"
    },
    {
        "is_body_part": False,
        "length": 30,
        "height": 20,
        "thickness": 4,
        "weight": 2.0,
        "price": 85,
        "ship_time": 36,
        "availability": 80,
        "mp_name": "Valvola di Scarico",
        "mp_description": "Valvola di scarico per moto ad alte prestazioni.",
        "mid_provider": 18,
        "year_from": 2020,
        "year_to": 2024,
        "builds_on": "KM,DC,YM"
    },
    {
        "is_body_part": False,
        "length": 35,
        "height": 15,
        "thickness": 4,
        "weight": 2.2,
        "price": 95,
        "ship_time": 48,
        "availability": 80,
        "mp_name": "Ammortizzatore Posteriore",
        "mp_description": "Ammortizzatore posteriore con regolazione a molla.",
        "mid_provider": 19,
        "year_from": 2021,
        "year_to": 2023,
        "builds_on": "KM,DC,YM"
    },
    {
        "is_body_part": False,
        "length": 25,
        "height": 20,
        "thickness": 4,
        "weight": 1.7,
        "price": 75,
        "ship_time": 36,
        "availability": 85,
        "mp_name": "Sistema di Lubrificazione",
        "mp_description": "Sistema di lubrificazione avanzato per motori sportivi.",
        "mid_provider": 17,
        "year_from": 2020,
        "year_to": 2023,
        "builds_on": "YM,KM,DC"
    }
]





# URL of the endpoint
url = "http://localhost:8000/parts/add_part.php"

# Function to send data
def send_data(data):
    headers = {'Content-Type': 'application/json'}
    try:
        response = requests.post(url, headers=headers, data=json.dumps(data))
        response.raise_for_status()  # Will raise an HTTPError for bad responses
        print(f"Success: {response.text}")
    except requests.exceptions.RequestException as e:
        print(f"Error: {e}")

# Send body parts
for part in body_parts:
    send_data(part)

# Send mechanical parts
for part in mechanical_parts:
    send_data(part)
